Algoritmo "area_do_retângulo"
// Autor(a)    : Bernardo Fernandes
// Data atual  : 21/9/2017
// Descrição   : Cálculo da area do retângulo
Var
   comprimento,largura,area: real
Inicio
  escreva("Qual o comprimento do retângulo?")
  leia(comprimento)
  escreva("Qual a largura do retângulo?")
  leia(largura)
  
area <- comprimento * largura
   escreva("A área é?", area)


Fimalgoritmo