Algoritmo "Média_3_notas"
// Autor(a)    : Bernardo Fernandes
// Data atual  : 21/9/2017
// Descrição   : Cálculo da média de 3 notas
Var
   nota1,nota2,nota3,media: real
Inicio
  escreva("Qual a nota 1?")
  leia(nota1)
  escreva("Qual a nota 2?")
  leia(nota2)
  escreva("Qual a nota 3?")
  leia(nota3)

media <- (nota1 + nota2 + nota3)/3
   escreva("A média é?", media)


Fimalgoritmo